src/Otus.Teaching.Pcf.Administration.UiWebHost/Models/ErrorViewModel.cs
using System;

namespace Otus.Teaching.Pcf.Administration.UiWebHost.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Otus.Teaching.Pcf.Administration.UiWebHost/Models/Roles/RoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Otus.Teaching.Pcf.Administration.UiWebHost.Models.Roles
{
    public class RoleViewModel
    {
        public Guid Id { get; set; }

        [Required(ErrorMessage = "Должно быть заполнено")]
        [Display(Name="Наименование")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Должно быть заполнено")]
        [Display(Name = "Комментарий")]
        public string Description { get; set; }
    }
}

src/Otus.Teaching.Pcf.Administration.UiWebHost/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Otus.Teaching.Pcf.Administration.UiWebHost.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Otus.Teaching.Pcf.Administration.UiWebHost.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Otus.Teaching.Pcf.Administration.UiWebHost/Controllers/RolesController.cs
using Microsoft.AspNetCore.Mvc;
using Otus.Teaching.Pcf.Administration.Core.Abstractions.Repositories;
using Otus.Teaching.Pcf.Administration.Core.Domain.Administration;
using Otus.Teaching.Pcf.Administration.UiWebHost.Extensions.Roles;
using Otus.Teaching.Pcf.Administration.UiWebHost.Models.Roles;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Otus.Teaching.Pcf.Administration.UiWebHost.Controllers
{
    public class RolesController : Controller
    {
        private readonly IRepository<Role> _rolesRepository;

        public RolesController(IRepository<Role> rolesRepository)
        {
            _rolesRepository = rolesRepository;
        }


        public async Task<IActionResult> Index()
        {
            var roles = await _rolesRepository.GetAllAsync();
            var rolesModel = roles.Select(x => x.ToViewModel()).ToList();

            return View(rolesModel);
        }


        [HttpGet]
        public async Task<IActionResult> Edit([FromRoute]Guid id)
        {
            var role = await _rolesRepository.GetByIdAsync(id);
            RoleViewModel viewModel = role.ToViewModel();
            return View(viewModel);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var existingRole = await _rolesRepository.GetByIdAsync(model.Id);
                
                existingRole.Name = model.Name;
                existingRole.Description = model.Description;
                
                await _rolesRepository.UpdateAsync(existingRole);
                
                return RedirectToAction("Index");
            }

            return View(model);

        }


        [HttpGet]
        public async Task<IActionResult> Add()
        {
            RoleViewModel viewModel = new RoleViewModel();
            return View(viewModel);
        }


        [HttpPost]
        public async Task<IActionResult> Add(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = model.ToDomainModel();
                await _rolesRepository.AddAsync(role);
                return RedirectToAction("Index");
            }

            return View(model);
            
        }


        [HttpGet]
        public async Task<IActionResult> Remove([FromRoute] Guid id)
        {
            var role = await _rolesRepository.GetByIdAsync(id);
            await _rolesRepository.DeleteAsync(role);
            return RedirectToAction("Index");
        }


        [HttpPost]
        public async Task<string> RemoveJQ( Guid id)
        {
            var role = await _rolesRepository.GetByIdAsync(id);
            await _rolesRepository.DeleteAsync(role);
            return Url.ActionLink("Index");
        }
    }
}

src/Otus.Teaching.Pcf.Administration.UiWebHost/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/Otus.Teaching.Pcf.Administration.UiWebHost/Views/Roles/Add.cshtml
@model Otus.Teaching.Pcf.Administration.UiWebHost.Models.Roles.RoleViewModel

@{
    Layout = "_Layout";
}

<h1>Добавить роль</h1>
<br />

<form method="post" action="Add">
    <table>
        <thead>
            <tr>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tr>
            <td>
                @Html.LabelFor(x => x.Name, new { @class = "control-label" })
            </td>
            <td>
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(x => x.Description, new { @class = "control-label" })
            </td>
            <td>
                @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Description, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                <input type="submit" value="Сохранить" />
            </td>
        </tr>
    </table>
</form>

src/Otus.Teaching.Pcf.Administration.UiWebHost/Views/Roles/Edit.cshtml
@model Otus.Teaching.Pcf.Administration.UiWebHost.Models.Roles.RoleViewModel

@{
    Layout = "_Layout";
}

<h1>Изменить роль</h1>
<br />

<form method="post" action="Edit">
    @Html.HiddenFor(x=>x.Id)
    <table>
        <thead>
            <tr>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tr>
            <td>
                @Html.LabelFor(x => x.Name, new { @class = "control-label" })
            </td>
            <td>
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(x => x.Description, new { @class = "control-label" })
            </td>
            <td>
                @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Description, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                <input type="submit" value="Сохранить" />
            </td>
        </tr>
    </table>
</form>

src/Otus.Teaching.Pcf.Administration.UiWebHost/Views/Roles/Index.cshtml
@model IList<Otus.Teaching.Pcf.Administration.UiWebHost.Models.Roles.RoleViewModel>

@{
    Layout = "_Layout";
}

<h1>Список ролей</h1>
<br />

<a class="btn btn-primary text-white" href="@Url.Action("Add", "Roles")">Добавить роль</a>
<br />
<br />

<table class="table">
    <thead>
        <tr>
            <th>ИД</th>
            <th>Наименование</th>
            <th>Комментарий</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var role in Model)
        {
            <tr>
                <td>@role.Id</td>
                <td>@role.Name</td>
                <td>@role.Description</td>
                <td>
                    <a class="btn btn-primary text-white" href="@Url.Action("Edit", "Roles", new { id = role.Id })">Изменить</a>
                    <a class="btn btn-primary text-white" href="@Url.Action("Remove", "Roles", new { id = role.Id })">Удалить</a>
                    <input type="button" class="btn btn-primary text-white role-del" data-id="@role.Id" value="Удалить JQ" />
                </td>
            </tr>
        }
    </tbody>
</table>


@section Scripts {

    <script type="text/javascript">

        $(document).ready(function () {

            $('.role-del').click(function () {

                var id = $(this).data('id');

                $.post('@Url.Action("RemoveJQ", "Roles")', { id: id })
                    .done(function (data) {
                        location.href = data;
                    });
            });

        });
    </script>
}

src/Otus.Teaching.Pcf.Administration.UiWebHost/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HW Базовые элементы фронтенда: Razor + jQuery + MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HW Базовые элементы фронтенда: Razor + jQuery + MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Роли</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HW Базовые элементы фронтенда: Razor + jQuery + MVC
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>